### ISSUE TITLE
Simple leaf properties are shown as expandable

### ISSUE THREAD

**Issue by stevenj** [asyncapi/html-template#57] opened 2020-08-27 04:34 UTC
#### Describe the bug
Simple properties that have no children are shown as expandable.

#### How to Reproduce
So i have a field defined like so:

```
"properties": {
    "sysoid": {
        "type": "string",
         "description": "The System OID of the Device."
   },
...
```
which is rendering in the generated HTML like so:
- Screenshots
![image](https://user-images.githubusercontent.com/764829/91384628-46749400-e859-11ea-99ae-7096e09ab0d0.png)

![image](https://user-images.githubusercontent.com/764829/91384542-1cbb6d00-e859-11ea-9d20-a70df56bbd5f.png)

This is effecting all leaf type properties, and not just strings.

#### Expected behavior
These leaf type properties should not be expandable.

**Comment by fmvilas** [comment] 2020-08-27 07:45
Thanks for reporting, @stevenj. I'm closing this issue since it's a duplicate of https://github.com/asyncapi/html-template/issues/50. Let's continue conversation there. Thanks!

**Closed by fmvilas** 2020-08-27 07:45 UTC
Labels: bug
